// PDF Export utility using browser print
// Creates a print-friendly view and triggers browser's print dialog

interface PrintOptions {
  title: string;
  subtitle?: string;
  companyName?: string;
  content: string;
}

export function exportToPDF({ title, subtitle, companyName = 'AluERP - Window & Door MFG', content }: PrintOptions) {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  printWindow.document.write(`
    <!DOCTYPE html>
    <html><head>
      <title>${title}</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Inter', Arial, sans-serif; color: #1a1a2e; padding: 40px; font-size: 12px; }
        .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 3px solid #2563eb; padding-bottom: 20px; margin-bottom: 24px; }
        .company { font-size: 20px; font-weight: 700; color: #2563eb; }
        .company-sub { font-size: 10px; color: #6b7280; margin-top: 2px; }
        .doc-title { font-size: 16px; font-weight: 600; text-align: right; }
        .doc-subtitle { font-size: 10px; color: #6b7280; text-align: right; margin-top: 2px; }
        .doc-date { font-size: 10px; color: #6b7280; text-align: right; margin-top: 4px; }
        table { width: 100%; border-collapse: collapse; margin: 16px 0; }
        th { background: #f1f5f9; padding: 8px 12px; text-align: left; font-size: 10px; font-weight: 600; text-transform: uppercase; color: #475569; border-bottom: 2px solid #e2e8f0; }
        td { padding: 8px 12px; border-bottom: 1px solid #f1f5f9; font-size: 11px; }
        tr:nth-child(even) { background: #fafbfc; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .font-bold { font-weight: 600; }
        .section-title { font-size: 14px; font-weight: 600; margin: 20px 0 10px; color: #1e293b; }
        .summary-row { display: flex; justify-content: space-between; padding: 4px 0; }
        .summary-label { color: #6b7280; }
        .summary-value { font-weight: 600; }
        .total-row { border-top: 2px solid #2563eb; padding-top: 8px; margin-top: 8px; font-size: 14px; }
        .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 9px; color: #9ca3af; text-align: center; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 10px; font-weight: 500; }
        .badge-success { background: #dcfce7; color: #166534; }
        .badge-warning { background: #fef3c7; color: #92400e; }
        .badge-danger { background: #fecaca; color: #991b1b; }
        .badge-info { background: #dbeafe; color: #1e40af; }
        @media print { body { padding: 20px; } }
      </style>
    </head><body>
      <div class="header">
        <div>
          <div class="company">${companyName}</div>
          <div class="company-sub">Addis Ababa, Ethiopia · +251-911-000000 · info@aluerp.com</div>
        </div>
        <div>
          <div class="doc-title">${title}</div>
          ${subtitle ? `<div class="doc-subtitle">${subtitle}</div>` : ''}
          <div class="doc-date">Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
        </div>
      </div>
      ${content}
      <div class="footer">
        Generated by AluERP · ${new Date().toLocaleString()} · This is a computer-generated document
      </div>
    </body></html>
  `);
  printWindow.document.close();
  setTimeout(() => printWindow.print(), 500);
}

export function generateQuotePDF(quote: { id: string; customerName: string; projectName: string; items: number; materialCost: number; laborCost: number; installCost: number; transportCost: number; cuttingFee?: number; discount?: number; subtotal: number; vat: number; total: number; date: string; validity: string; status: string; finishType?: string; }) {
  const content = `
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:20px;">
      <div><strong>Quote #:</strong> ${quote.id}</div>
      <div><strong>Customer:</strong> ${quote.customerName}</div>
      <div><strong>Project:</strong> ${quote.projectName}</div>
      <div><strong>Status:</strong> <span class="badge badge-${quote.status === 'Accepted' ? 'success' : quote.status === 'Rejected' ? 'danger' : 'warning'}">${quote.status}</span></div>
      <div><strong>Date:</strong> ${quote.date}</div>
      <div><strong>Valid Until:</strong> ${quote.validity}</div>
      ${quote.finishType ? `<div><strong>Finish:</strong> ${quote.finishType}</div>` : ''}
    </div>
    <table>
      <tr><th>Description</th><th class="text-right">Amount (ETB)</th></tr>
      <tr><td>Material Cost</td><td class="text-right">${quote.materialCost.toLocaleString()}</td></tr>
      <tr><td>Labor Cost</td><td class="text-right">${quote.laborCost.toLocaleString()}</td></tr>
      <tr><td>Installation Cost</td><td class="text-right">${quote.installCost.toLocaleString()}</td></tr>
      <tr><td>Transport Cost</td><td class="text-right">${quote.transportCost.toLocaleString()}</td></tr>
      ${quote.cuttingFee ? `<tr><td>Cutting Fee</td><td class="text-right">${quote.cuttingFee.toLocaleString()}</td></tr>` : ''}
      ${quote.discount ? `<tr><td>Discount</td><td class="text-right">-${quote.discount.toLocaleString()}</td></tr>` : ''}
      <tr><td class="font-bold">Subtotal</td><td class="text-right font-bold">${quote.subtotal.toLocaleString()}</td></tr>
      <tr><td>VAT (15%)</td><td class="text-right">${quote.vat.toLocaleString()}</td></tr>
      <tr style="background:#eff6ff;"><td class="font-bold" style="font-size:14px;">TOTAL</td><td class="text-right font-bold" style="font-size:14px;color:#2563eb;">ETB ${quote.total.toLocaleString()}</td></tr>
    </table>
    <div style="margin-top:30px;padding:16px;background:#f8fafc;border-radius:8px;">
      <p style="font-size:10px;color:#6b7280;">Terms & Conditions:</p>
      <ul style="font-size:10px;color:#6b7280;margin-top:8px;padding-left:16px;">
        <li>Prices valid until ${quote.validity}</li>
        <li>50% advance payment required upon order confirmation</li>
        <li>Balance due upon delivery/installation completion</li>
        <li>Warranty: 5 years on aluminum, 2 years on hardware</li>
      </ul>
    </div>
  `;
  exportToPDF({ title: `Quotation ${quote.id}`, subtitle: `For: ${quote.customerName}`, content });
}

export function generateOrderInvoicePDF(order: { id: string; customerName: string; orderDate: string; requestedDelivery: string; status: string; paymentStatus: string; paymentMethod?: string; items: Array<{ productName: string; quantity: number; unitPrice: number; lineTotal: number }>; subtotal: number; tax: number; total: number; paid: number; balance: number; }) {
  const itemRows = order.items.map(i => `
    <tr><td>${i.productName}</td><td class="text-center">${i.quantity}</td><td class="text-right">${i.unitPrice.toLocaleString()}</td><td class="text-right">${i.lineTotal.toLocaleString()}</td></tr>
  `).join('');
  const content = `
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:20px;">
      <div><strong>Invoice/Order #:</strong> ${order.id}</div>
      <div><strong>Customer:</strong> ${order.customerName}</div>
      <div><strong>Order Date:</strong> ${order.orderDate}</div>
      <div><strong>Delivery:</strong> ${order.requestedDelivery}</div>
      <div><strong>Status:</strong> <span class="badge badge-info">${order.status}</span></div>
      <div><strong>Payment:</strong> <span class="badge badge-${order.paymentStatus === 'Paid' ? 'success' : order.paymentStatus === 'Partial' ? 'warning' : 'danger'}">${order.paymentStatus}</span></div>
    </div>
    <table>
      <tr><th>Product</th><th class="text-center">Qty</th><th class="text-right">Unit Price (ETB)</th><th class="text-right">Total (ETB)</th></tr>
      ${itemRows}
      <tr><td colspan="3" class="font-bold">Subtotal</td><td class="text-right font-bold">${order.subtotal.toLocaleString()}</td></tr>
      <tr><td colspan="3">Tax (15%)</td><td class="text-right">${order.tax.toLocaleString()}</td></tr>
      <tr style="background:#eff6ff;"><td colspan="3" class="font-bold" style="font-size:14px;">TOTAL</td><td class="text-right font-bold" style="font-size:14px;color:#2563eb;">ETB ${order.total.toLocaleString()}</td></tr>
      <tr><td colspan="3">Amount Paid</td><td class="text-right" style="color:#16a34a;">ETB ${order.paid.toLocaleString()}</td></tr>
      ${order.balance > 0 ? `<tr><td colspan="3" class="font-bold">Balance Due</td><td class="text-right font-bold" style="color:#dc2626;">ETB ${order.balance.toLocaleString()}</td></tr>` : ''}
    </table>
  `;
  exportToPDF({ title: `Invoice ${order.id}`, subtitle: `Bill to: ${order.customerName}`, content });
}

export function generateReportPDF(title: string, tableHeaders: string[], rows: string[][]) {
  const headerCells = tableHeaders.map(h => `<th>${h}</th>`).join('');
  const bodyRows = rows.map(r => `<tr>${r.map(c => `<td>${c}</td>`).join('')}</tr>`).join('');
  const content = `<table><tr>${headerCells}</tr>${bodyRows}</table>`;
  exportToPDF({ title, content });
}
